### ISSUE TITLE
Extension page repository link is broken

### ISSUE THREAD

**Issue by Jaeiya** [CB0rghi/vscode-autosave-ext#1]
The repository link on the extensions page [here](https://marketplace.visualstudio.com/items?itemName=codista.vscode-autosave&ssr=false) links to: `https://github.com/CB0rghi/vscode-autosave/ext` instead of `https://github.com/CB0rghi/vscode-autosave-ext`

Your extension however is amazing ❤️

**Comment by CB0rghi** [comment]
Thank you so much for this feedback, really appreciate it!

Already fixed, will be deployed ASAP.

Also, I know there's still room for improvement, will keep working on it whenever possible 😁
